### ISSUE TITLE
Crash: Wilderness Map-to-Map Travel

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#188] opened 2021-06-17 01:34 UTC
Zabutor ran into a crash entering a new wilderness map somewhere on the approach to Amon Rudh—might have even been entering the wilderness map with the Amon Rudh staircase itself, wasn't spectating.

Anyway, it crashed the game; he was able to reload his save without problems, but it had placed him back at the start of the map he had been in the process of leaving.

He was able to redo his progress and and proceed to the next map alright on the second go, so whatever the problem was I would guess it was related to the generic map generation in some way.

**Comment by NickMcConnell** [comment] 2021-06-17 09:55
Probably related to #144, I'm putting this as Ongoing but I need to remember to get back and check those.

**Comment by backwardsEric** [comment] 2021-07-07 15:32
One source for crashes is the delete_monster() call in the super paranoid section of populate():

1. Compile with USE_STATS set (I used "cd src; make -f Makefile.osx OPT="-DUSE_STATS -g -O0").
2. Run.  Select a hobbit as a new character.
3. Go to Anduin Vale 1.  Use 'ctrl-a' followed by 'D' to start the disconnection stats debugging command.  Generate a bunch of levels, 1000 or so should do the trick.
4. That crashed for me at cave-square.c:1106 (square_in_bounds()) called from delete_monster()) with a NULL pointer for the chunk; cave was NULL in delete_monster().

I did a bit of follow-up on the source for the breaks in the boundary wall.  After replacing the part in populate() that redraws the boundary wall with assertion checks that the wall was in place and rerunning the executable, the first assertion failure was for a bit of road (c->squares[grid.y][grid.x].feat was 38) that had replaced a grid of the boundary wall.

**Comment by NickMcConnell** [comment] 2021-07-17 00:37
This is apparently only happening on angband.live, and only when there is a player ghost on the level, and always fully recoverable by just reloading.  It is happening in new_level_display_update(), after the autosave and before the redraw completes.  Logic would indicate it's somewhere in update_monsters(), but I'm buggered if I can work out where.

**Comment by backwardsEric** [comment] 2021-07-17 17:40
I don't know if it's relevant, but why does prepare_ghost() access the lore with a fixed index, "lore = &l_list[PLAYER_GHOST_RACE];", rather than the passed in race index?  get_lore(), what update_mon() uses, pulls up the lore by the index stored in the race structure.

**Comment by NickMcConnell** [comment] 2021-07-17 21:49
Yes, I've been vaguely thinking about that, and have suspected the problem is lore-related.  I'll have a look.

**Comment by NickMcConnell** [comment] 2021-07-17 22:52
Looks like ad058e5c1 has fixed this, closing 😀

**Closed by NickMcConnell** 2021-07-17 22:52 UTC
